### ISSUE TITLE
Uhhhhhh... You leaked your bot's token???

### ISSUE THREAD

**Issue by ACA30** [DiscordBotList/Luca#12]
Just..... just.... Why?? How...? You leaked your bot's token. In `bot.js`. Please, fix it before your bot gets jacked.

-Nate

**Comment by tonkku107** [comment]
![](https://camo.githubusercontent.com/c1937bfb969a5c49ac9484b0b62dca858db7ad02/68747470733a2f2f63646e2e6265747465727474762e6e65742f656d6f74652f3536376230306336316464626531373836363838613633332f3378)

**Comment by zSnails** [comment]
yardim
