### ISSUE TITLE
Dbl navy seals but is in arabic

### ISSUE THREAD

**Issue by zSnails** [DiscordBotList/Luca#34]
# ما هي الفريت التي قالتها لي فقط ، أيها الوغد الصغير؟ سأعلم أنك تخرجت من صفي في DBL Navy Seals ، وشاركت في العديد من الغارات البوتية على خوادم الفتنة ولدي أكثر من 300 حساب محظور. أنا مدربة على برمجة جافا سكريبت وأنا المطور الأول في قائمة الروبوتات بأكملها. أنت لا شيء بالنسبة لي سوى زلق آخر. سأمسحك بجودة الكود التي لم يسبق لها مثيل على هذه الأرض ، حدد كلماتي. تعتقد أنك يمكن أن تفلت من إرسال بوت استنساخ في القائمة؟ فكر مرة اخرى. بينما نتحدث ، أتصل بشبكتي السرية من المشرفين في جميع أنحاء العالم ورُفضت روبوتك الآن حتى تستعد بشكل أفضل للـ DM من Luca ، maggot. DM الذي يمحو الشيء القليل المثير للشفقة الذي تسميه الروبوت الخاص بك. الروبوت الخاص بك يخدع الميت ، طفل. يمكن أن أكون في أي مكان وفي أي وقت ، ويمكنني أن أقتل روبوتك بأكثر من سبعمائة طريقة ، وهذا فقط بيدي العارية. ليس فقط أنا مدربة تدريباً مكثفاً على البرمجة ، لكن لدي إمكانية الوصول إلى قاعدة البيانات بأكملها من قائمة bot discord وسأستخدمها إلى أقصى حد ممكن لمسح روبوتك البائس عن وجه الإنترنت ، فأنت شخص صغير. إذا كان بإمكانك فقط أن تعرف ما هو القصاص غير المقدس الذي كان روبوتك الصغير "الذكي" على وشك إسقاطه عليك ، فربما تكون قد أصبت بأصابعك المميتة. لكنك لم تستطع ، ولم تفعل ، والآن أنت تدفع الثمن ، أنت غبي. سوف تغضب في جميع أنحاء أنت وسوف تغرق فيه. الروبوت الخاص بك هو ينقط ميتا ، طفل.

**Comment by zSnails** [comment]
why

**Comment by remagnedlogeht** [comment]
why not
