### ISSUE TITLE
Token is publicly available

### ISSUE THREAD

**Issue by szymex73** [DiscordBotList/Luca#6]
Hi,
I see that thebot'stoken is hard coded into the files and visible when opening them. I think you should hide it to remove the risk of someone stealing the token to do something you wouldn't want.

**Comment by tonkku107** [comment]
![](https://camo.githubusercontent.com/c1937bfb969a5c49ac9484b0b62dca858db7ad02/68747470733a2f2f63646e2e6265747465727474762e6e65742f656d6f74652f3536376230306336316464626531373836363838613633332f3378)

**Comment by LetsDoughNut** [comment]
>Actually giving a shit
