### ISSUE TITLE
Move all of the duplicate message listeners to if/else if/else

### ISSUE THREAD

**Issue by AlgoRythm-Dylan** [DiscordBotList/Luca#7]
Having a different `Discord.on('message', function (message) {}` for each command isn't the best way of going about things. Instead, you should have only one message listener which uses if/else if/else to deal with the various commands. I have not run the bot, but reading the code, I assume it always replies with "Unknown command!" if the message starts with an "!":
```
Discord.on('message', function (message) {
   if (message.content.startsWith('!')) {
        return message.reply('Unknown command!');
    } 
});
```
Since all commands start with an "!", all commands will be unknown. The solution is if/else if/else:
```
// Determine if the message is a command before this point.
if(command == "hi"){
    // Code
}
else if(command == "other-command"){
    // Code
}
else{
    // Reply with "unknown command"
}

**Comment by tonkku107** [comment]
I am sorry my friend for you wandering your way into this meme without context...
